import Head from "next/head";
import { Container, Link, Text, Image, Spacer, Input, Button, PressEvent } from "@nextui-org/react";
import { useState } from "react";
var distance = require("jaro-winkler");
var levenshtein = require("damerau-levenshtein");

export default function Home() {
	const [term1, setTerm1] = useState<string>("cocaine");
	const [term2, setTerm2] = useState<string>("cociane");
	const [similarity, setSimilarity] = useState<number>(0.967);
	const [edits, setEdits] = useState<number>(1);

	function compare(_: PressEvent) {
		const sim: number = distance(term1, term2);
		setSimilarity(sim);
		const edits: number = levenshtein(term1, term2).steps;
		setEdits(edits);
	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Container display="flex" direction="column" justify="center" alignItems="center">
					<Text h1 color="primary">
						UK IPOP Fuzzy Drug Searcher
					</Text>
					<Spacer y={1} />
					<Image src="/imgs/logo.png" alt="logo" width={300} height={300} objectFit="cover" />
					<Text h5>
						This tool allows you to compare two terms (drugs) and see how similar they are. It
						ideally should be used as an explorative tool to identfiy a valid threshold for the
						similarity score to use in a fuzzy search. Hopefully the fuzzy search would be our{" "}
						<Link href="https://github.com/UK-IPOP/drug-extraction">drug extraction tool</Link>. For
						more information, please see the User Guide at the above link.
					</Text>
					<Spacer y={1} />
					<Container display="flex" direction="row" justify="center" alignItems="center">
						<Input
							underlined
							labelPlaceholder="Term 1"
							color="primary"
							value={term1}
							onChange={(e) => {
								e.preventDefault();
								setTerm1(e.target.value);
							}}
						/>
						<Spacer x={1} />
						<Input
							underlined
							labelPlaceholder="Term 2"
							color="primary"
							value={term2}
							onChange={(e) => {
								e.preventDefault();
								setTerm2(e.target.value);
							}}
						/>
					</Container>
					<Spacer y={1} />
					<Button size="lg" color="primary" onPress={compare}>
						Compare
					</Button>
					<Spacer y={1} />
					<Text h5>
						The terms are {(similarity * 100).toPrecision(3)}% similar
						<br />
						The terms are {edits} edits away
					</Text>
					<Spacer y={3} />
					<Text h5>
						Maintained by{" "}
						<Link href="https://pharmacy.uky.edu/office-research-operations/cornerstones/research-centers/ipop">
							UK IPOP
						</Link>
					</Text>
				</Container>
			</main>
		</>
	);
}
