import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Spacer, Text } from '@nextui-org/react'
import Button from '@mui/material/Button';
import RocketLaunchIcon from '@mui/icons-material/RocketLaunch';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text h2 className={styles.title}>
          Welcome to the <a href="https://pharmacy.uky.edu/office-research-operations/cornerstones/research-centers/ipop">UK-IPOP</a> Drug Extractor
        </Text>
        <Spacer />
        <Image src="/images/logo.png" alt="Logo" height="300" width="300" objectFit="cover" />
        <Spacer />
        <div className={styles.title}>
          <Button endIcon={<RocketLaunchIcon />} color="primary" variant="outlined" size="large" href="/interactive">Get Started</Button>
        </div>
        <Text className={styles.description}>
          This is a website to search for and extract drugs from text records.
          <br />
          It is a companion to the command-line <a href="https://github.com/UK-IPOP/drug-extraction/tree/main/cli" target="_blank>">tool</a>.
          <br />
          If you have questions on specific details please see the <a href="https://github.com/UK-IPOP/drug-extraction" target="_blank>">documentation</a>.
          <br />
          <Text b>Please use either Chrome or Firefox for this program to work properly.</Text>
        </Text>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <a href="https://pharmacy.uky.edu/office-research-operations/cornerstones/research-centers/ipop">UK-IPOP</a>
      </footer>
    </div >
  )
}

export default Home
