site_name: Drug Extraction
site_url: https://uk-ipop.github.io/drug-extraction/

repo_url: https://github.com/UK-IPOP/drug-extraction
repo_name: UK-IPOP/drug-extraction

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
  palette:
    primary: indigo
    accent: deep orange
  # logo: IPOP-logo.png
  # favicon: IPOP-logo.png

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

copyright: Copyright &copy; 2021 UK-IPOP
